seed: 42

# Model
model_name: DATv1
nf: 64
enc_res_blocks: 5
dec_res_blocks: 5
mlp_ratio: 2

# Data
flow_dir: flow
distill_bwd: True                            # True: learn ft0  False: learn f01
data_name: Vimeo90K                          # Vimeo90K, X4K
root: datasets/vimeo_triplet                 # vimeo_triplet, X4K1000FPS
crop_h: 224
crop_w: 224
batch_size: 2                                # Per GPU
num_workers: 8

# Training
start_lr: 2.0e-4
resume_epoch: 0
num_epochs: 1000
valid_freq_epoch: 1
val_datasets:
  - vimeo90k
save_best_benchmark: vimeo90k


# Logging
img_summary_freq: 10
metric_summary_freq: 10
save_latest_freq: 2000
