seed: 42

# Model
model_name: DATwConstantnCv1
nf: 72
enc_res_blocks: 5
dec_res_blocks: 10
mlp_ratio: 2

# Losses
distill_lambda: 0.01

# Data
data_name: Vimeo90KwFlow                     # Vimeo90K, X4K
root: datasets/vimeo_triplet                 # vimeo_triplet, X4K1000FPS
flow_dir: flow
distill_bwd: True                            # True: learn ft0  False: learn f01
crop_h: 256
crop_w: 256

# Training
num_epochs: 2000
batch_size: 12                                # Per GPU
num_workers: 8

# Optimizer
start_lr: 2.0e-4
end_lr: 1.0e-5
weight_decay: 1.0e-4
last_lr_decay_iter: 600000


# Validation
valid_freq_epoch: 1
val_datasets:
  - vimeo90k
  - ucf101
save_best_benchmark: vimeo90k


# Logging
img_summary_freq: 1000
metric_summary_freq: 100
save_latest_freq: 2000
save_every_freq_epoch: 25
